[workspace]
members = [".", "machine", "neander"]

[package]
name = "niau"
version = "0.1.0"
authors = ["brunoczim <brunoczim@gmail.com>"]
edition = "2018"

[dependencies]
neander = { path = "neander" }
